#!/usr/bin/env bash

## Copyright 2013 Elliot Chow

## Licensed under the Apache License, Version 2.0 (the "License")
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at

## http://www.apache.org/licenses/LICENSE-2.0

## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

R_VERSION='2.15.3'

if test -f "R-$R_VERSION/_BUILD_SUCCESS" ; then
    echo "R-$R_VERSION has already been built - continuing..."
else
    echo 'download and build R 2.15.3...'
    rm -rf R-$R_VERSION
    curl -o R-$R_VERSION.tar.gz "http://cran.cnr.berkeley.edu/src/base/R-"`echo $R_VERSION | awk -F'.' '{print $1}' `"/R-$R_VERSION.tar.gz" && \
    tar xvzf R-$R_VERSION.tar.gz && \
    cd R-$R_VERSION && \
    ./configure --with-x=no && \
    make && \
    touch _BUILD_SUCCESS && \
    cd ..
fi

if test -f "R-$R_VERSION/_BUILD_SUCCESS" ; then
    echo "R-$R_VERSION was build successfully!"
else
    echo "ERROR: R-$R_VERSION was not built successfully"
    exit 1
fi
