#!/usr/bin/env bash

## Copyright 2013 Elliot Chow

## Licensed under the Apache License, Version 2.0 (the "License")
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at

## http://www.apache.org/licenses/LICENSE-2.0

## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

R_VERSION='2.15.3'

if test -f "R-$R_VERSION/_BUILD_SUCCESS" ; then
    rm -f R-$R_VERSION/_PACKAGE_SUCCESS
    echo 'modifying R_HOME_DIR and copying libraries...'
    sed 0,/'R_HOME_DIR=.*'/{s/R_HOME_DIR=.*/'R_HOME_DIR=$(dirname $(readlink -f $0))\/..'/} R-$R_VERSION/bin/R > R.tmp && \
        (test -f R-$R_VERSION/bin/R.bak && echo 'R.bak already exists' || mv -v R-$R_VERSION/bin/R R-$R_VERSION/bin/R.bak) && \
        mv -v R.tmp R-$R_VERSION/bin/R && \
        chmod a+rx R-$R_VERSION/bin/R && \
        ls `ldd R-$R_VERSION/bin/exec/R | awk -F'=>' '{print $2}' | awk -F'(' '!($0 ~ /not found/){print $1}' | awk -F'(' '/^[ ]*$/ {next} {print $0}'` | xargs -I {} cp -v {} R-$R_VERSION/lib/. && \
        (test -f R-$R_VERSION/lib/libgfortran.so.3 || (test -f /usr/lib/x86_64-linux-gnu/libgfortran.so.3 && cp -v /usr/lib/x86_64-linux-gnu/libgfortran.so.3 R-$R_VERSION/lib/.) || echo "WARNING: cannot find libgfortran.so.3") && \
        (test -f R-$R_VERSION/lib/libquadmath.so.0 || (test -f /usr/lib/x86_64-linux-gnu/libquadmath.so.0 && cp -v /usr/lib/x86_64-linux-gnu/libquadmath.so.0 R-$R_VERSION/lib/.) || echo "WARNING: cannot find libquadmath.so.0") && \

        cd R-$R_VERSION && \
        tar -czf ../R-$R_VERSION-build.tar.gz . && \
        cd .. && \
        touch R-$R_VERSION/_PACKAGE_SUCCESS
else
    echo "ERROR: R-$R_VERSION was not built successfully"
    exit 1
fi

if test -f "R-$R_VERSION/_PACKAGE_SUCCESS" ; then
    echo "R-$R_VERSION was successfully packaged!"
else
    echo "ERROR: R-$R_VERSION was not packaged properly"
    exit 1
fi

